---
package_name_jdk: java-1.8.0-openjdk-devel
maven_version: 3.5.4
maven_src: /usr/local/src
maven_home: /usr/local/maven
maven_sh_path: /etc/profile.d/maven.sh
nexus_version: 3
nexus_home: /usr/local/nexus
nexus_src: /usr/local/src/nexus
java_home_cmd: readlink -f /usr/bin/java | sed "s:/jre/bin/java::"
nexus_user: nexus
nexus_group: nexus
nexus_script: /etc/systemd/system/nexus.service
nexus_template: nexus.service.template
